### PR TITLE
Conversion from BICEP to Terraform - Part 1

### PR DESCRIPTION
**Pull request by dayland**
In this PR, we have converted the existing infrastructure to terraform in place of BICEP. 

As this is Part 1 of a series of PRs for Terraform, we only support the following scenarios at this time:
- This only support deployment to a new environment, you cannot upgrade a previously deployed BICEP environment
- This only supports Commercial installs at the moment
   - Both existing and auto deployed AOAI instances are working
- This version support running under CI/CD pipelines
   
 The following scenarios will be applied in subsequent PRs
 - US Gov deployments
 - Documentation and process for upgrade/migration from BICEP to TF environment

### CODE REVIEW

**Comment by asbanger** [comment]
Thank you for publishing PR. Came across with following deployment error during deployment

│ Error: "resource_group_name" cannot be blank
│ 
│   with azurerm_resource_group_template_deployment.customer_attribution[0],
│   on main.tf line 438, in resource "azurerm_resource_group_template_deployment" "customer_attribution":
│  438:   resource_group_name = var.resourceGroupName
│

**Comment by asbanger** [comment]
Deployment has been blocked with following errors!

Error: Invalid count argument
│ 
│   on main.tf line 431, in module "openAiRoleMgmt":
│  431:   count = module.entraObjects.azure_ad_web_app_client_id == module.entraObjects.azure_ad_mgmt_app_client_id ? 0 : 1
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply
│ only the resources that the count depends on.
╵
make: *** [Makefile:25: infrastructure] Error 1

**Comment by dayland** [comment]
> Deployment has been blocked with following errors!
> 
> Error: Invalid count argument │ │ on main.tf line 431, in module "openAiRoleMgmt": │ 431: count = module.entraObjects.azure_ad_web_app_client_id == module.entraObjects.azure_ad_mgmt_app_client_id ? 0 : 1 │ │ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply │ only the resources that the count depends on. ╵ make: *** [Makefile:25: infrastructure] Error 1

Fixed in latest commit

**Review by ryonsteele — APPROVED** [review]
Tested a good bit yesterday, saw same role assignment error as Ashvith. 
That was all I saw.

**Review by georearl — APPROVED** [review]

**Pull request merged**
