### PR TITLE
Geearl/7021 tag filter

### PR DESCRIPTION
**Pull request by georearl**
This PR adds the following features on the upload status page:

- presents a dropdown of unique tag names and allows a selection. Filtering on the selection will be part of a future PR once we have agreed how to query across 2 cosmos containers most efficiently
- It adds the option to select/deselect individual rows in the documents table and individual items

### CODE REVIEW

**Review by mausolfj — COMMENTED** [review]
Thanks for adding tag filters. It wasn't clear to me how you determined the minWidth of columns 2-6 in /app/frontend/src/componenets/FileStatus/DocumentsDetailedList. Can you elaborate or explain?

**Comment by georearl** [comment]
> Thanks for adding tag filters. It wasn't clear to me how you determined the minWidth of columns 2-6 in /app/frontend/src/componenets/FileStatus/DocumentsDetailedList. Can you elaborate or explain?

**Comment by georearl** [comment]
> Thanks for adding tag filters. It wasn't clear to me how you determined the minWidth of columns 2-6 in /app/frontend/src/componenets/FileStatus/DocumentsDetailedList. Can you elaborate or explain?

widths for columns 2-6 are as they were all along apart from the folders. I kept that column at a reasonable length, but the user has the option to change manually

**Review by ryonsteele — APPROVED** [review]

**Review by mausolfj — APPROVED** [review]
Thanks for updating

**Review by mausolfj — DISMISSED** [review]
Thanks for adding tag filters

**Review by ryonsteele — APPROVED** [review]

**Pull request merged**
